# Homework 3  - Tryout pandas and numpy

Copy this notebook. Rename it as: YOURNAME-Homework-panda-numpy-Sept-2017

with your name replacing yourname and  replaced with the date you submit or to the last part.

Do the homeworks problems below.

Upload your completed jupyter notebook to your github site and send me the url via the elearning site as your homework submission. Please note that you need to do your own 3.4, and 3.5 if you share data and analysis from others then you cannot get more than a 3.  

## Homework 3.1

### 3.1.a
Load the data from: http://opendata.dc.gov/datasets that I have include in this github   
into a dataframe.  ( The file has been is available in directory ./data/ccp_current_csv.csv )

In [4]:
import pandas as pd
data=pd.read_csv('./data/ccp_current_csv.csv' )
data

STREET QUADRANT            FROMINTERSECTION  \
0               13th St       NW                  Kennedy St   
1                  S St       NW            North Capitol St   
2      Rhode Island Ave       NE            Brentwood Rd (W)   
3               Mill Rd       NW                     27th St   
4      Rhode Island Ave       NE            Brentwood Rd (M)   
5             Mellon St       SE                      5th St   
6          Nebraska Ave       NW              Northampton St   
7           Military Rd       NW                     30th St   
8          Nebraska Ave       NW                   Oliver St   
9               16th St       NW                  Alaska Ave   
10         Shoemaker St       NW                 Linnean Ave   
11         Underwood St       NW             Piney Branch Rd   
12             Elder St       NW                      7th St   
13              26th St       NW              Northampton St   
14               4th St       NW              Madison St (N)   
15         Underwood Pl       NW            North Capitol St   
16              20th St       NW                 Columbia Rd   
17          Quintana Pl       NE                      3rd St   
18         Tuckerman St       NE                  Kansas Ave   
19              Eads St       NE                     45th St   
20               4th St       SE                  Newcomb St   
21              Belt Rd       NW                  Jenifer St   
22            Oneida St       NE           New Hampshire Ave   
23      Carrollsburg Pl       SW                        O St   
24              23rd St       NW          Washington Cir (N)   
25           Kanawha St       NW                    Utah Ave   
26      Piney Branch Rd       NW                Underwood St   
27              30th St       NW               Stephenson Pl   
28              32nd St       NW                 Woodland Dr   
29              33rd St       NW            Broad Branch Ter   
..                  ...      ...                         ...   
435      New Jersey Ave       NW                        F St   
436             15th St       NE                     Ames Pl   
437     East Capitol St       BN                        C St   
438         Randolph St       NE                     25th Pl   
439    South Dakota Ave       NE                Delafield St   
440          Wheeler Rd       SE                 Congress St   
441      New Jersey Ave       NW                        H St   
442     Mount Olivet Rd       NE               Brentwood Pky   
443              Oak St       NW                     16th St   
444        Michigan Ave       NE                     14th St   
445                C St       NE                     20th St   
446        Virginia Ave       SE                  6th St (S)   
447              Oak St       NW                Brown St (N)   
448         Florida Ave       NE                New York Ave   
449  North Carolina Ave       NE         East Capitol St (E)   
450            Elder St       NW                      8th St   
451          Benning Rd       SE                        G St   
452           School St       SW                      4th St   
453             18th St       NW                        M St   
454       Longfellow St       NW                     16th St   
455             10th St       NW                        M St   
456          Woodley Rd       NW             Connecticut Ave   
457          Woodley Rd       NW           Cathedral Ave (E)   
458              3rd St       SW            Independence Ave   
459             16th St       NW                 Primrose Rd   
460          Woodley Rd       NW                  Woodley Pl   
461         Western Ave       NW         Chevy Chase Cir (E)   
462             49th St       NW                   Fulton St   
463       Quackenbos St       NE           New Hampshire Ave   
464    North Capitol St       BN  Hawaii Ave  Rock Creek Chu   

                 TOINTERSECTION  NOOFBLOCKS     

### 3.1.a  what is its shape and what does that mean?

In [5]:
data.shape

(465, 27)

## Homework 3.2
 What are the number of rows in each 'QUADRANT' ?

In [43]:
data['QUADRANT'].value_counts()

NW    195
NE    163
SE     84
BN     12
SW     11
Name: QUADRANT, dtype: int64

## Homework 3.3 - Array math demonstration 
For two arrarys  

a= [1,2,3,4]  type=float

b= [5,6,7,8]  type=float

Peform the following array operations using numpy   
( show both operational use of numpy and functional (example addition operation => + vs addition function => numbpy.add() )


# FUNCTIONAL USE

### 3.3.1 addition a+b 

In [7]:
import numpy as np
a= np.array ([1,2,3,4],dtype=float)
b= np.array ([5,6,7,8],dtype=float)
np.add(a,b)

array([  6.,   8.,  10.,  12.])

### 3.3.2 subtraction a-b

In [8]:
np.subtract(a,b)

array([-4., -4., -4., -4.])

### 3.3.3 multiplication a*b

In [9]:
np.multiply(a,b)

array([  5.,  12.,  21.,  32.])

### 3.3.4 divsion a/b

In [10]:
np.divide(a,b)

array([ 0.2       ,  0.33333333,  0.42857143,  0.5       ])

### 3.3.5 modulo  a%b

In [11]:
np.mod(a,b)

array([ 1.,  2.,  3.,  4.])

### 3.3.6 power  a^b

In [12]:
np.power(a,b)

array([  1.00000000e+00,   6.40000000e+01,   2.18700000e+03,
         6.55360000e+04])

# OPERATIONAL USE

In [13]:
a+b#3.3.1 addition a+b

array([  6.,   8.,  10.,  12.])

In [14]:
a-b#3.3.2 subtraction a-b

array([-4., -4., -4., -4.])

In [15]:
a*b#3.3.3 multiplication a*b

array([  5.,  12.,  21.,  32.])

In [16]:
a/b# 3.3.4 divsion a/b

array([ 0.2       ,  0.33333333,  0.42857143,  0.5       ])

In [17]:
a%b#3.3.5 modulo a%b

array([ 1.,  2.,  3.,  4.])

In [18]:
a**b#3.3.6 power a^b

array([  1.00000000e+00,   6.40000000e+01,   2.18700000e+03,
         6.55360000e+04])

## Homework 3.4
Find your own data and load it into a dataframe

In [19]:
dataframe=pd.read_csv("H:\Datasets\cwurData.csv")
dataframe

world_rank                                        institution  \
0              1                                 Harvard University   
1              2              Massachusetts Institute of Technology   
2              3                                Stanford University   
3              4                            University of Cambridge   
4              5                 California Institute of Technology   
5              6                               Princeton University   
6              7                               University of Oxford   
7              8                                    Yale University   
8              9                                Columbia University   
9             10                 University of California, Berkeley   
10            11                              University of Chicago   
11            12                                 Cornell University   
12            13                         University of Pennsylvania   
13            14                                University of Tokyo   
14            15                           Johns Hopkins University   
15            16    Swiss Federal Institute of Technology in Zurich   
16            17                                   Kyoto University   
17            18                      Weizmann Institute of Science   
18            19              University of California, Los Angeles   
19            20                University of California, San Diego   
20            21                             Rockefeller University   
21            22                     Hebrew University of Jerusalem   
22            23                                New York University   
23            24            University of California, San Francisco   
24            25                    University of Wisconsin–Madison   
25            26         University of Illinois at Urbana–Champaign   
26            27                                    Duke University   
27            28                            Imperial College London   
28            29    University of Texas Southwestern Medical Center   
29            30                      University of Texas at Austin   
...          ...                                                ...   
2170         971                         Fu Jen Catholic University   
2171         972                            Hunan Normal University   
2172         973  Ulsan National Institute of Science and Techno...   
2173         974                  Federal University of Santa Maria   
2174         975                                Shenzhen University   
2175         976                         Tianjin Medical University   
2176         977                   Beijing University of Technology   
2177         978              University of Reims Champagne-Ardenne   
2178         979                                 Yuan Ze University   
2179         980     University of Chemistry and Technology, Prague   
2180         981                             University of Limerick   
2181         982                     China Medical University (PRC)   
2182         983                               Feng Chia University   
2183         984                  Zhejiang University of Technology   
2184         985                       Novosibirsk State University   
2185         986                            University of Bucharest   
2186         987                            Babeș-Bolyai University   
2187         988                                Mansoura University   
2188         989              University of Pau and Pays de l'Adour   
2189         990                            Henan Normal University   
2190         991                                  Xidian University   
2191         992                        Federal University of Bahia   
2192         993                      Southwest Jiaotong University   
2193         994                                 Ryerson University   
2194         995              




## Homework 3.5
Provide an interesting analysis of the data columns ( frequency or averages )

In [20]:
dataframe.set_index("institution", inplace=True)#setting Index
dataframe.head()

world_rank         country  \
institution                                                         
Harvard University                              1             USA   
Massachusetts Institute of Technology           2             USA   
Stanford University                             3             USA   
University of Cambridge                         4  United Kingdom   
California Institute of Technology              5             USA   

                                       national_rank  quality_of_education  \
institution                                                                  
Harvard University                                 1                     7   
Massachusetts Institute of Technology              2                     9   
Stanford University                                3                    17   
University of Cambridge                            1                    10   
California Institute of Technology                 4                     2   

                                       alumni_employment  quality_of_faculty  \
institution                                                                    
Harvard University                                     9                   1   
Massachusetts Institute of Technology                 17                   3   
Stanford University                                   11                   5   
University of Cambridge                               24                   4   
California Institute of Technology                    29                   7   

                                       publications  influence  citations  \
institution                                                                 
Harvard University                                1          1          1   
Massachusetts Institute of Technology            12          4          4   
Stanford University                               4          2          2   
University of Cambridge                          16         16         11   
California Institute of Technology               37         22         22   

                                       broad_impact  patents   score  year  
institution                                                                 
Harvard University                              NaN        5  100.00  2012  
Massachusetts Institute of Technology           NaN        1   91.67  2012  
Stanford University                             NaN       15   89.50  2012  
University of Cambridge                         NaN       50   86.17  2012  
California Institute of Technology              NaN       18   85.21  2012

In [21]:
print dataframe['country']#selecting desired coloumn

institution
Harvard University                                               USA
Massachusetts Institute of Technology                            USA
Stanford University                                              USA
University of Cambridge                               United Kingdom
California Institute of Technology                               USA
Princeton University                                             USA
University of Oxford                                  United Kingdom
Yale University                                                  USA
Columbia University                                              USA
University of California, Berkeley                               USA
University of Chicago                                            USA
Cornell University                                               USA
University of Pennsylvania                                       USA
University of Tokyo                                            Japan
Johns Hopkins Universi

In [22]:
dataframe[dataframe['country']== "USA"]#displaying USA universities(sub setting data)
        

world_rank country  \
institution                                                              
Harvard University                                           1     USA   
Massachusetts Institute of Technology                        2     USA   
Stanford University                                          3     USA   
California Institute of Technology                           5     USA   
Princeton University                                         6     USA   
Yale University                                              8     USA   
Columbia University                                          9     USA   
University of California, Berkeley                          10     USA   
University of Chicago                                       11     USA   
Cornell University                                          12     USA   
University of Pennsylvania                                  13     USA   
Johns Hopkins University                                    15     USA   
University of California, Los Angeles                       19     USA   
University of California, San Diego                         20     USA   
Rockefeller University                                      21     USA   
New York University                                         23     USA   
University of California, San Francisco                     24     USA   
University of Wisconsin–Madison                             25     USA   
University of Illinois at Urbana–Champaign                  26     USA   
Duke University                                             27     USA   
University of Texas Southwestern Medical Center             29     USA   
University of Texas at Austin                               30     USA   
Northwestern University                                     33     USA   
University of Michigan, Ann Arbor                           34     USA   
University of North Carolina at Chapel Hill                 36     USA   
Washington University in St. Louis                          37     USA   
University of Utah                                          38     USA   
University of Washington - Seattle                          39     USA   
University of California, Santa Barbara                     40     USA   
Purdue University, West Lafayette                           42     USA   
...                                                        ...     ...   
Howard University                                          719     USA   
Rutgers, The State University of New Jersey - N...         723     USA   
University of Memphis                                      746     USA   
University of Missouri–St. Louis                           748     USA   
University of Alabama in Huntsville                        752     USA   
University of Mississippi Medical Center                   754     USA   
New Jersey Institute of Technology                         761     USA   
East Carolina University                                   762     USA   
Northern Arizona University                                766     USA   
University of North Texas, Denton                          778     USA   
Michigan Technological University                          790     USA   
North Dakota State University - Main Campus                792     USA   
University of North Carolina at Charlotte                  794     USA   
Bowling Green State University                             809     USA   
Florida Institute of Technology                            823     USA   
University of Massachusetts Boston                         825     USA   
The Catholic University of America                         832     USA   
Wright State University - Dayton                           833     USA   
Clarkson University                                        835     USA   
University of South Alabama                                844     USA   
Hunter College                                             850     USA   
Florida Atlantic University                             

In [23]:
dataframe[dataframe['national_rank']==1]#displaying top national universities(Subsetting Data)

world_rank  \
institution                                                   
Harvard University                                        1   
University of Cambridge                                   4   
University of Tokyo                                      14   
Swiss Federal Institute of Technology in Zurich          16   
Weizmann Institute of Science                            18   
University of Toronto                                    35   
University of Paris-Sud                                  48   
University of Edinburgh                                  60   
Karolinska Institute                                     70   
Seoul National University                                75   
Sapienza University of Rome                              77   
Ruprecht Karl University of Heidelberg                   82   
Leiden University                                        85   
University of Helsinki                                   89   
University of Oslo                                       91   
University of Queensland                                 92   
University of Copenhagen                                 93   
Harvard University                                        1   
University of Oxford                                      3   
University of Tokyo                                      14   
Swiss Federal Institute of Technology in Zurich          18   
Hebrew University of Jerusalem                           21   
University of Toronto                                    29   
University of Paris-Sud                                  36   
Seoul National University                                40   
Karolinska Institute                                     60   
Sapienza University of Rome                              62   
Ludwig Maximilian University of Munich                   67   
University of Copenhagen                                 68   
University of Oslo                                       81   
...                                                     ...   
University of Auckland                                  266   
Charles University in Prague                            270   
National and Kapodistrian University of Athens          301   
Chulalongkorn University                                311   
National Autonomous University of Mexico                334   
Indian Institute of Technology Delhi                    341   
University of Buenos Aires                              367   
Pontifical Catholic University of Chile                 376   
Jagiellonian University                                 451   
Eötvös Loránd University                                458   
University of Iceland                                   461   
Middle East Technical University                        470   
University of Science, Malaysia                         482   
University of Ljubljana                                 504   
University of Tartu                                     537   
University of Zagreb                                    551   
King Saud University                                    569   
University of Los Andes (Colombia)                      652   
American University of Beirut                           682   
Comenius University in Bratislava                       685   
Sharif University of Technology                         697   
University of Belgrade                                  726   
Vilnius University                                      791   
Cairo University                                        796   
Sofia University                                        845   
Makerere University                                     869   
University of Cyprus                                    928   
United Arab Emirates University                         950   
University of Puerto Rico at Mayagüez                   962   
University of Bucharest                                 986   

                                                              country  \
instit

In [24]:
dataframe.iloc[0:20, 1:6]# iloc[row slicing, column slicing]

country  \
institution                                                       
Harvard University                                          USA   
Massachusetts Institute of Technology                       USA   
Stanford University                                         USA   
University of Cambridge                          United Kingdom   
California Institute of Technology                          USA   
Princeton University                                        USA   
University of Oxford                             United Kingdom   
Yale University                                             USA   
Columbia University                                         USA   
University of California, Berkeley                          USA   
University of Chicago                                       USA   
Cornell University                                          USA   
University of Pennsylvania                                  USA   
University of Tokyo                                       Japan   
Johns Hopkins University                                    USA   
Swiss Federal Institute of Technology in Zurich     Switzerland   
Kyoto University                                          Japan   
Weizmann Institute of Science                            Israel   
University of California, Los Angeles                       USA   
University of California, San Diego                         USA   

                                                 national_rank  \
institution                                                      
Harvard University                                           1   
Massachusetts Institute of Technology                        2   
Stanford University                                          3   
University of Cambridge                                      1   
California Institute of Technology                           4   
Princeton University                                         5   
University of Oxford                                         2   
Yale University                                              6   
Columbia University                                          7   
University of California, Berkeley                           8   
University of Chicago                                        9   
Cornell University                                          10   
University of Pennsylvania                                  11   
University of Tokyo                                          1   
Johns Hopkins University                                    12   
Swiss Federal Institute of Technology in Zurich              1   
Kyoto University                                             2   
Weizmann Institute of Science                                1   
University of California, Los Angeles                       13   
University of California, San Diego                         14   

                                                 quality_of_education  \
institution                                                             
Harvard University                                                  7   
Massachusetts Institute of Technology                               9   
Stanford University                                                17   
University of Cambridge                                            10   
California Institute of Technology                                  2   
Princeton University                                                8   
University of Oxford                                               13   
Yale University                                                    14   
Columbia University                                                23   
University of California, Berkeley                                 16   
University of Chicago                                              15   
Cornell University                                                 21   
University of Pennsylvania                                         31   
University of Tokyo              

In [25]:
dataframe.iloc[3, 1]# Syntax for iloc indexing to finding a specific data element

'United Kingdom'

In [26]:
pd.isnull(dataframe)#identify all locations in the dataframe that have null (missing or NaN) data values.

world_rank  country  \
institution                                                               
Harvard University                                       False    False   
Massachusetts Institute of Technology                    False    False   
Stanford University                                      False    False   
University of Cambridge                                  False    False   
California Institute of Technology                       False    False   
Princeton University                                     False    False   
University of Oxford                                     False    False   
Yale University                                          False    False   
Columbia University                                      False    False   
University of California, Berkeley                       False    False   
University of Chicago                                    False    False   
Cornell University                                       False    False   
University of Pennsylvania                               False    False   
University of Tokyo                                      False    False   
Johns Hopkins University                                 False    False   
Swiss Federal Institute of Technology in Zurich          False    False   
Kyoto University                                         False    False   
Weizmann Institute of Science                            False    False   
University of California, Los Angeles                    False    False   
University of California, San Diego                      False    False   
Rockefeller University                                   False    False   
Hebrew University of Jerusalem                           False    False   
New York University                                      False    False   
University of California, San Francisco                  False    False   
University of Wisconsin–Madison                          False    False   
University of Illinois at Urbana–Champaign               False    False   
Duke University                                          False    False   
Imperial College London                                  False    False   
University of Texas Southwestern Medical Center          False    False   
University of Texas at Austin                            False    False   
...                                                        ...      ...   
Fu Jen Catholic University                               False    False   
Hunan Normal University                                  False    False   
Ulsan National Institute of Science and Technology       False    False   
Federal University of Santa Maria                        False    False   
Shenzhen University                                      False    False   
Tianjin Medical University                               False    False   
Beijing University of Technology                         False    False   
University of Reims Champagne-Ardenne                    False    False   
Yuan Ze University                                       False    False   
University of Chemistry and Technology, Prague           False    False   
University of Limerick                                   False    False   
China Medical University (PRC)                           False    False   
Feng Chia University                                     False    False   
Zhejiang University of Technology                        False    False   
Novosibirsk State University                             False    False   
University of Bucharest                                  False    False   
Babeș-Bolyai University                                  False    False   
Mansoura University                                      False    False   
University of Pau and Pays de l'Adour                    False    False   
Henan Normal University                                  False    False   
Xidian University                                        False    False   
Fe

In [27]:
datacopy = dataframe.copy()#creation of copy
datacopy

world_rank  \
institution                                                      
Harvard University                                           1   
Massachusetts Institute of Technology                        2   
Stanford University                                          3   
University of Cambridge                                      4   
California Institute of Technology                           5   
Princeton University                                         6   
University of Oxford                                         7   
Yale University                                              8   
Columbia University                                          9   
University of California, Berkeley                          10   
University of Chicago                                       11   
Cornell University                                          12   
University of Pennsylvania                                  13   
University of Tokyo                                         14   
Johns Hopkins University                                    15   
Swiss Federal Institute of Technology in Zurich             16   
Kyoto University                                            17   
Weizmann Institute of Science                               18   
University of California, Los Angeles                       19   
University of California, San Diego                         20   
Rockefeller University                                      21   
Hebrew University of Jerusalem                              22   
New York University                                         23   
University of California, San Francisco                     24   
University of Wisconsin–Madison                             25   
University of Illinois at Urbana–Champaign                  26   
Duke University                                             27   
Imperial College London                                     28   
University of Texas Southwestern Medical Center             29   
University of Texas at Austin                               30   
...                                                        ...   
Fu Jen Catholic University                                 971   
Hunan Normal University                                    972   
Ulsan National Institute of Science and Technology         973   
Federal University of Santa Maria                          974   
Shenzhen University                                        975   
Tianjin Medical University                                 976   
Beijing University of Technology                           977   
University of Reims Champagne-Ardenne                      978   
Yuan Ze University                                         979   
University of Chemistry and Technology, Prague             980   
University of Limerick                                     981   
China Medical University (PRC)                             982   
Feng Chia University                                       983   
Zhejiang University of Technology                          984   
Novosibirsk State University                               985   
University of Bucharest                                    986   
Babeș-Bolyai University                                    987   
Mansoura University                                        988   
University of Pau and Pays de l'Adour                      989   
Henan Normal University                                    990   
Xidian University                                          991   
Federal University of Bahia                                992   
Southwest Jiaotong University                              993   
Ryerson University                                         994   
King Abdulaziz University                                  995   
University of the Algarve                                  996   
Alexandria University                                      997   
Federal University of Ceará                                998   
University of A Coruña    

In [28]:
dataframe.drop(dataframe.index[[1,4]])#droping selected rows

world_rank  \
institution                                                      
Harvard University                                           1   
Stanford University                                          3   
University of Cambridge                                      4   
Princeton University                                         6   
University of Oxford                                         7   
Yale University                                              8   
Columbia University                                          9   
University of California, Berkeley                          10   
University of Chicago                                       11   
Cornell University                                          12   
University of Pennsylvania                                  13   
University of Tokyo                                         14   
Johns Hopkins University                                    15   
Swiss Federal Institute of Technology in Zurich             16   
Kyoto University                                            17   
Weizmann Institute of Science                               18   
University of California, Los Angeles                       19   
University of California, San Diego                         20   
Rockefeller University                                      21   
Hebrew University of Jerusalem                              22   
New York University                                         23   
University of California, San Francisco                     24   
University of Wisconsin–Madison                             25   
University of Illinois at Urbana–Champaign                  26   
Duke University                                             27   
Imperial College London                                     28   
University of Texas Southwestern Medical Center             29   
University of Texas at Austin                               30   
University College London                                   31   
Osaka University                                            32   
...                                                        ...   
Fu Jen Catholic University                                 971   
Hunan Normal University                                    972   
Ulsan National Institute of Science and Technology         973   
Federal University of Santa Maria                          974   
Shenzhen University                                        975   
Tianjin Medical University                                 976   
Beijing University of Technology                           977   
University of Reims Champagne-Ardenne                      978   
Yuan Ze University                                         979   
University of Chemistry and Technology, Prague             980   
University of Limerick                                     981   
China Medical University (PRC)                             982   
Feng Chia University                                       983   
Zhejiang University of Technology                          984   
Novosibirsk State University                               985   
University of Bucharest                                    986   
Babeș-Bolyai University                                    987   
Mansoura University                                        988   
University of Pau and Pays de l'Adour                      989   
Henan Normal University                                    990   
Xidian University                                          991   
Federal University of Bahia                                992   
Southwest Jiaotong University                              993   
Ryerson University                                         994   
King Abdulaziz University                                  995   
University of the Algarve                                  996   
Alexandria University                                      997   
Federal University of Ceará                                998   
University of A Coruña    

In [29]:
dataframe.drop('world_rank')#dropping of selected coloumn by name

world_rank  \
institution                                                      
Harvard University                                           1   
Massachusetts Institute of Technology                        2   
Stanford University                                          3   
University of Cambridge                                      4   
California Institute of Technology                           5   
Princeton University                                         6   
University of Oxford                                         7   
Yale University                                              8   
Columbia University                                          9   
University of California, Berkeley                          10   
University of Chicago                                       11   
Cornell University                                          12   
University of Pennsylvania                                  13   
University of Tokyo                                         14   
Johns Hopkins University                                    15   
Swiss Federal Institute of Technology in Zurich             16   
Kyoto University                                            17   
Weizmann Institute of Science                               18   
University of California, Los Angeles                       19   
University of California, San Diego                         20   
Rockefeller University                                      21   
Hebrew University of Jerusalem                              22   
New York University                                         23   
University of California, San Francisco                     24   
University of Wisconsin–Madison                             25   
University of Illinois at Urbana–Champaign                  26   
Duke University                                             27   
Imperial College London                                     28   
University of Texas Southwestern Medical Center             29   
University of Texas at Austin                               30   
...                                                        ...   
Fu Jen Catholic University                                 971   
Hunan Normal University                                    972   
Ulsan National Institute of Science and Technology         973   
Federal University of Santa Maria                          974   
Shenzhen University                                        975   
Tianjin Medical University                                 976   
Beijing University of Technology                           977   
University of Reims Champagne-Ardenne                      978   
Yuan Ze University                                         979   
University of Chemistry and Technology, Prague             980   
University of Limerick                                     981   
China Medical University (PRC)                             982   
Feng Chia University                                       983   
Zhejiang University of Technology                          984   
Novosibirsk State University                               985   
University of Bucharest                                    986   
Babeș-Bolyai University                                    987   
Mansoura University                                        988   
University of Pau and Pays de l'Adour                      989   
Henan Normal University                                    990   
Xidian University                                          991   
Federal University of Bahia                                992   
Southwest Jiaotong University                              993   
Ryerson University                                         994   
King Abdulaziz University                                  995   
University of the Algarve                                  996   
Alexandria University                                      997   
Federal University of Ceará                                998   
University of A Coruña    

In [30]:
dataframe.drop(dataframe.columns[[0, 3, 5]], axis=1)#drop by column number 

country  \
institution                                                          
Harvard University                                             USA   
Massachusetts Institute of Technology                          USA   
Stanford University                                            USA   
University of Cambridge                             United Kingdom   
California Institute of Technology                             USA   
Princeton University                                           USA   
University of Oxford                                United Kingdom   
Yale University                                                USA   
Columbia University                                            USA   
University of California, Berkeley                             USA   
University of Chicago                                          USA   
Cornell University                                             USA   
University of Pennsylvania                                     USA   
University of Tokyo                                          Japan   
Johns Hopkins University                                       USA   
Swiss Federal Institute of Technology in Zurich        Switzerland   
Kyoto University                                             Japan   
Weizmann Institute of Science                               Israel   
University of California, Los Angeles                          USA   
University of California, San Diego                            USA   
Rockefeller University                                         USA   
Hebrew University of Jerusalem                              Israel   
New York University                                            USA   
University of California, San Francisco                        USA   
University of Wisconsin–Madison                                USA   
University of Illinois at Urbana–Champaign                     USA   
Duke University                                                USA   
Imperial College London                             United Kingdom   
University of Texas Southwestern Medical Center                USA   
University of Texas at Austin                                  USA   
...                                                            ...   
Fu Jen Catholic University                                  Taiwan   
Hunan Normal University                                      China   
Ulsan National Institute of Science and Technology     South Korea   
Federal University of Santa Maria                           Brazil   
Shenzhen University                                          China   
Tianjin Medical University                                   China   
Beijing University of Technology                             China   
University of Reims Champagne-Ardenne                       France   
Yuan Ze University                                          Taiwan   
University of Chemistry and Technology, Prague      Czech Republic   
University of Limerick                                     Ireland   
China Medical University (PRC)                               China   
Feng Chia University                                        Taiwan   
Zhejiang University of Technology                            China   
Novosibirsk State University                                Russia   
University of Bucharest                                    Romania   
Babeș-Bolyai University                                    Romania   
Mansoura University                                          Egypt   
University of Pau and Pays de l'Adour                       France   
Henan Normal University                                      China   
Xidian University                                            China   
Federal University of Bahia                                 Brazil   
Southwest Jiaotong University                                China   
Ryerson University                                          Canada   
King Abdulaziz University                             Saudi Arabia   

# REFERENCES:

https://stackoverflow.com/questions/13411544/delete-column-from-pandas-dataframe-using-python-del
https://www.kaggle.com/mylesoneill/world-university-rankings/data
https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.value_counts.html
http://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.DataFrame.shape.html
http://pythonhow.com/data-analysis-with-python-pandas/
http://www.scipy-lectures.org/intro/numpy/operations.html#basic-operations
