# Homework 3  - Tryout pandas and numpy

Copy this notebook. Rename it as: YOURNAME-Homework-panda-numpy-Sept-2017

with your name replacing yourname and  replaced with the date you submit or to the last part.

Do the homeworks problems below.

Upload your completed jupyter notebook to your github site and send me the url via the elearning site as your homework submission. Please note that you need to do your own 3.4, and 3.5 if you share data and analysis from others then you cannot get more than a 3.  

## Homework 3.1

### 3.1.a
Load the data from: http://opendata.dc.gov/datasets that I have include in this github   
into a dataframe.  ( The file has been is available in directory ./data/ccp_current_csv.csv )

In [27]:
import pandas as pd
data=pd.read_csv('./data/ccp_current_csv.csv' )
print(data)

                 STREET QUADRANT            FROMINTERSECTION  \
0               13th St       NW                  Kennedy St   
1                  S St       NW            North Capitol St   
2      Rhode Island Ave       NE            Brentwood Rd (W)   
3               Mill Rd       NW                     27th St   
4      Rhode Island Ave       NE            Brentwood Rd (M)   
5             Mellon St       SE                      5th St   
6          Nebraska Ave       NW              Northampton St   
7           Military Rd       NW                     30th St   
8          Nebraska Ave       NW                   Oliver St   
9               16th St       NW                  Alaska Ave   
10         Shoemaker St       NW                 Linnean Ave   
11         Underwood St       NW             Piney Branch Rd   
12             Elder St       NW                      7th St   
13              26th St       NW              Northampton St   
14               4th St       NW        

### 3.1.a  what is its shape and what does that mean?

In [28]:
data.shape

(465, 27)

## Homework 3.2
 What are the number of rows in each 'QUADRANT' ?

In [30]:
data['QUADRANT'].value_counts
 

<bound method Series.value_counts of 0      NW
1      NW
2      NE
3      NW
4      NE
5      SE
6      NW
7      NW
8      NW
9      NW
10     NW
11     NW
12     NW
13     NW
14     NW
15     NW
16     NW
17     NE
18     NE
19     NE
20     SE
21     NW
22     NE
23     SW
24     NW
25     NW
26     NW
27     NW
28     NW
29     NW
       ..
435    NW
436    NE
437    BN
438    NE
439    NE
440    SE
441    NW
442    NE
443    NW
444    NE
445    NE
446    SE
447    NW
448    NE
449    NE
450    NW
451    SE
452    SW
453    NW
454    NW
455    NW
456    NW
457    NW
458    SW
459    NW
460    NW
461    NW
462    NW
463    NE
464    BN
Name: QUADRANT, Length: 465, dtype: object>

## Homework 3.3 - Array math demonstration 
For two arrarys  

a= [1,2,3,4]  type=float

b= [5,6,7,8]  type=float

Peform the following array operations using numpy   
( show both operational use of numpy and functional (example addition operation => + vs addition function => numbpy.add() )


# FUNCTIONAL USE

### 3.3.1 addition a+b 

In [10]:
import numpy as np
a= np.array ([1,2,3,4],dtype=float)
b= np.array ([5,6,7,8],dtype=float)
np.add(a,b)

array([  6.,   8.,  10.,  12.])

### 3.3.2 subtraction a-b

In [31]:
np.subtract(a,b)

array([-4., -4., -4., -4.])

### 3.3.3 multiplication a*b

In [32]:
np.multiply(a,b)

array([  5.,  12.,  21.,  32.])

### 3.3.4 divsion a/b

In [17]:
np.divide(a,b)

array([ 0.2       ,  0.33333333,  0.42857143,  0.5       ])

### 3.3.5 modulo  a%b

In [33]:
np.mod(a,b)

array([ 1.,  2.,  3.,  4.])

### 3.3.6 power  a^b

In [21]:
np.power(a,b)

array([  1.00000000e+00,   6.40000000e+01,   2.18700000e+03,
         6.55360000e+04])

# OPERATIONAL USE

In [34]:
a+b#3.3.1 addition a+b

array([  6.,   8.,  10.,  12.])

In [35]:
a-b#3.3.2 subtraction a-b

array([-4., -4., -4., -4.])

In [36]:
a*b#3.3.3 multiplication a*b

array([  5.,  12.,  21.,  32.])

In [41]:
a/b# 3.3.4 divsion a/b

array([ 0.2       ,  0.33333333,  0.42857143,  0.5       ])

In [38]:
a%b#3.3.5 modulo a%b

array([ 1.,  2.,  3.,  4.])

In [40]:
a**b#3.3.6 power a^b

array([  1.00000000e+00,   6.40000000e+01,   2.18700000e+03,
         6.55360000e+04])

## Homework 3.4
Find your own data and load it into a dataframe

## Homework 3.5
Provide an interesting analysis of the data columns ( frequency or averages )